In [1]:
import numpy as np
a = np.array([2,4,6,8])
a

array([2, 4, 6, 8])

In [2]:
import numpy as np
b = np.array([[2,4,6,8],[3,6,9,12],[4,8,12,16],[5,10,15,20]])
b
type(b)


numpy.ndarray

In [3]:
type(b)
len(b)

4

In [4]:
b[0:]

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20]])

In [5]:
b=np.zeros(2)
b

array([0., 0.])

In [6]:
c=np.ones(2)
c

array([1., 1.])

In [7]:
d = np.empty(3)
d

array([1.00132653e-307, 6.23040373e-307, 1.02360935e-306])

In [8]:
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [9]:
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [10]:
g=np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
h=np.linspace(0,10, num=5)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
i = np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [13]:
i = np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((3,4)

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_2760/4293787472.py, line 1)

In [ ]:
np.empty((3,4))

In [ ]:
c= np.arange(24).reshape(2, 3, 4)
c

In [ ]:
import numpy as np
food=np.array(["a","b","c"])
food

In [ ]:
prize=np.array([2,3,4])
prize

In [ ]:
food[1]

In [ ]:
prize.mean()

In [ ]:
#yaha pr empty ceel ya one

np.empty(5)

In [ ]:
np.arange(2,20)

In [ ]:
np.arange(5, 55, 5)

In [ ]:
h=np.linspace(0,10, num=5)
h

In [ ]:
np.linspace(1, 100, num=10)

In [ ]:
np.linspace(1, 100, num=50)

In [ ]:
import numpy as np
np.ones(5, dtype=np.int64)

In [16]:
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

#Array


In [20]:
a=np.array([10,12,15,6.7,3.4,9.2])
a.sort()
a

array([ 3.4,  6.7,  9.2, 10. , 12. , 15. ])

In [21]:
a=np.array([10,12,15,6.7,3.4,9.2])
a

array([10. , 12. , 15. ,  6.7,  3.4,  9.2])

In [22]:
b=np.array([0,1,5,6.7,4.6,9.8,3.3 ])
b

array([0. , 1. , 5. , 6.7, 4.6, 9.8, 3.3])

In [24]:
c=np.concatenate((a,b))
c

array([10. , 12. , 15. ,  6.7,  3.4,  9.2,  0. ,  1. ,  5. ,  6.7,  4.6,
        9.8,  3.3])

In [25]:
c.sort()
c

array([ 0. ,  1. ,  3.3,  3.4,  4.6,  5. ,  6.7,  6.7,  9.2,  9.8, 10. ,
       12. , 15. ])

In [26]:
# 2-D arrays


In [27]:
b = np.array([[2,4,6,8],[3,6,9,12],[4,8,12,16],[5,10,15,20]])
b


array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20]])

In [28]:
a = np.array([[2,4,6,8],[3,6,9,12]])
a

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [29]:
b=([4,8,12,16],[5,10,15,20])
b

([4, 8, 12, 16], [5, 10, 15, 20])

In [36]:
c=np.concatenate((a,b),axis=0)
c

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20]])

In [39]:
a = np.array([[[2,4,6,8],
              [3,6,9,12]],
             
            [[4,8,12,16],
            [5,10,15,20]],
             
             [[0,1,2,3],
             [4,5,6,7]]])
a

array([[[ 2,  4,  6,  8],
        [ 3,  6,  9, 12]],

       [[ 4,  8, 12, 16],
        [ 5, 10, 15, 20]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]]])

In [43]:
a.ndim

3

In [ ]:
a = np.array([[[2,4,6,8],
              [3,6,9,12]],
             
            [[4,8,12,16],

In [48]:
b = np.array([[2,4,6],
              [3,6,9],
              [4,8,12]])
b

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [49]:
b.ndim

2

In [50]:
b.size #number of elements

9

In [51]:
b.shape

(3, 3)

In [58]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
np.reshape(a,newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [63]:
#1D into 2D
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
a



array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
a.shape

(9,)

In [66]:
b=a[np.newaxis, :]
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [67]:
b.shape

(1, 9)

In [68]:
b.ndim

2

In [69]:
c= a[:]
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
c= a[:, np.newaxis]
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [71]:
a[2:6]

array([2, 3, 4, 5])

In [72]:
a[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [73]:
a*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [74]:
a.sum()

36

In [75]:
a.mean(0)

4.0

####jupyter